--!strict
-- ReplicatedStorage/Shared/Types
-- Canonical configuration, saved-state, and network contracts shared across boundaries.

export type MaterialEntry = {
	total: number,
}

export type Element = "Fire" | "Water" | "Earth" | "Air" | "Light" | "Dark"

export type MaterialDef = {
	displayName: string,
	category: string,
	guiColor: string,
	thumbnail: string,
	description: string,
	launchEnabled: boolean,
	-- Required by launch validation; retained prototype IDs have no launch economy metadata.
	element: Element?,
	stackLimit: number?,
	buyGold: number?,
	sellGold: number?,
}

-- Inactive prototype definitions remain optional until their future update is designed.
export type ConsumableDef = {
	displayName: string?,
	thumbnail: string?,
	description: string?,
	rarity: string?,
	category: string?,
	value: number?,
	effect: string?,
}

export type ConsumableEntry = {
	consumableId: string?,
	quantity: number?,
	total: number?,
}

export type MythlingSpawnConfiguration = {
	targetActive: number,
	refillDeadlineSeconds: number,
	refillRetrySeconds: number,
	captureTickSeconds: number,
	ringVerticalAllowanceStuds: number,
	zonePadding: number, -- studs
	boundaryClearance: number,
	maxPlacementTries: number,
	fallbackStepStuds: number,
	rarityWeights: { [string]: number },
	expireSeconds: { [string]: number },
	formExpireSeconds: { [string]: number },
	defaultExpireSeconds: number,
}

-- One owned mythling, as persisted under the player document's `mythlings` section.
export type MythlingEntry = {
	typeId: string,
	variantId: string,
	claimedAt: number,
	level: number?,
	xp: number?,
	-- Private earned batch credit; optional only for retained prototypes, never a copied rate.
	pendingXp: number?,
	standId: number?,
	-- Legacy v2 cursor, consumed by the v3 migration. New work belongs to the stand.
	lastCollectionAt: number?,
}

export type MythlingProduction = {
	materialId: string,
	materialsPerMinute: number,
	baseCapacity: number,
}

export type MythlingVariant = {
	model: string,
	thumbnail: string,
}

export type MythlingEvolutionDefinition = { targetFormId: string, requiredLevel: number }
export type MythlingSaleDefinition = { gold: number }

-- Launch business metadata; presentation and active prototype spawning are separate concerns.
-- The dictionary key is a permanent form ID, not the unique ID of a player-owned instance.
export type MythlingFormDef = {
	element: Element,
	rarity: string,
	evolutionStage: number,
	baseYieldPerHour: number,
	captureProgressPerSecond: number,
	captureDecayPerSecond: number,
	evolution: MythlingEvolutionDefinition?,
	sale: MythlingSaleDefinition,
}

-- Retained prototype metadata, keyed by existing saved typeId; not the launch form catalogue.
export type MythlingDef = {
	displayName: string,
	rarity: string,
	sizeClass: string,
	zoneRadius: number,
	fillRate: number,
	drainRate: number,
	description: string,
	production: MythlingProduction,
	variants: { [string]: MythlingVariant },
}

export type EquipmentProfile = {
	displayName: string,
	rarity: string,
	thumbnail: string,
	description: string,
	kind: "PrimaryWeapon" | "Shield",
	modelName: string,
	staminaCost: number?,
	cooldownSeconds: number?,
	swingDurationSeconds: number?,
	animationId: string?,
	hitStartFallbackSeconds: number?,
	contactWindowSeconds: number?,
	hitStopSeconds: number?,
	reachStuds: number?,
	serverToleranceStuds: number?,
	requireLineOfSight: boolean?,
	planarKnockback: number?,
	verticalKnockback: number?,
	tumbleAngularSpeed: number?,
	launchControlSeconds: number?,
	maximumReactionSeconds: number?,
	landingRecoverySeconds: number?,
	airTrailSeconds: number?,
	impactSoundId: string?,
	impactStaminaCost: number?,
	minimumGuardStamina: number?,
	raiseSeconds: number?,
	raiseTimeoutSeconds: number?,
	lowerSeconds: number?,
	lowerTimeoutSeconds: number?,
	blockArcDegrees: number?,
	slideKnockback: number?,
	slideDurationSeconds: number?,
	raiseAnimationId: string?,
	holdAnimationId: string?,
	lowerAnimationId: string?,
}

export type EquipmentConfiguration = {
	presentationDefaults: {
		cooldownSeconds: number,
		swingDurationSeconds: number,
		raiseSeconds: number,
		raiseTimeoutSeconds: number,
		lowerSeconds: number,
		lowerTimeoutSeconds: number,
		hitStartFallbackSeconds: number,
		contactWindowSeconds: number,
		slideDurationSeconds: number,
		launchControlSeconds: number,
		maximumReactionSeconds: number,
		landingRecoverySeconds: number,
		shieldSlideFullSpeedFraction: number,
	},
	combat: {
		staminaMaximum: number,
		staminaSpawn: number,
		staminaRegenPerSecond: number,
		knockbackImmunitySeconds: number,
		arenaHeightAllowanceStuds: number,
	},
	profiles: { [string]: EquipmentProfile },
}

export type TransactionValues = { [string]: string | number | boolean }
export type TransactionOutcome = { ok: boolean, code: string?, values: TransactionValues? }
export type TransactionRequest = {
	id: string,
	expectedRevision: number,
	operation: string,
	-- Generated by the owning server service from the validated request, never trusted from a client.
	signature: string,
}
export type TransactionResult = {
	ok: boolean,
	code: string?,
	values: TransactionValues?,
	revision: number,
	replayed: boolean?,
}
export type TransactionState = {
	revision: number,
	receipts: {
		[string]: {
			expectedRevision: number,
			operation: string,
			signature: string,
			result: TransactionResult,
		},
	},
}

-- Reservation bookkeeping only; crafting start/completion gameplay is a separate task.
export type CraftingJob = {
	status: "Active" | "Completed" | "Cancelled",
	reservations: { equipment: number, materials: { [string]: number } },
}

export type EquipmentEntry = {
	definitionId: string,
	finishId: string?,
	isStarterGrant: boolean?,
}

export type CraftingStationRecord = { id: string, craftingStationId: string }

export type ShrineUpgradeCost = { gold: number, materialQuantity: number }
export type ShrineLevelDef = {
	capacity: number,
	workerSlots: number,
	-- Paid when entering this level, not when leaving it. Absent at the initial level.
	upgradeCost: ShrineUpgradeCost?,
}

-- Static construction, output, and level metadata; never copied into owned Shrine records.
export type ShrineDef = {
	displayName: string,
	element: Element,
	materialId: string,
	buildGoldCost: number,
	initialLevel: number,
	maxLevel: number,
	levels: { [number]: ShrineLevelDef },
}

export type ShrineRecord = {
	id: string,
	shrineId: string,
	buildSlotId: number,
	level: number,
	-- Optional only at the legacy/load boundary; prepared schema-7 records require all four.
	stored: number?,
	progress: number?,
	newWork: number?,
	workerIdsBySlot: { [string]: string }?,
}

-- One common schedule; Shrine records never own a second independently reset clock.
export type ProductionClock = {
	lastAccruedAt: number,
	nextBatchAt: number,
	lastOnlineCheckpointAt: number?,
	offlineSince: number?,
}

export type BuildShrineRequest = {
	requestId: string,
	expectedRevision: number,
	shrineId: string,
	expectedGoldCost: number,
}

export type AssignShrineWorkerRequest = {
	requestId: string,
	expectedRevision: number,
	shrineInstanceId: string,
	slotId: number,
	workerId: string,
}

export type RemoveShrineWorkerRequest = {
	requestId: string,
	expectedRevision: number,
	shrineInstanceId: string,
	slotId: number,
	expectedWorkerId: string,
}

export type CollectShrineRequest = {
	requestId: string,
	expectedRevision: number,
	shrineInstanceId: string,
	expectedMaterialId: string,
}

export type UpgradeShrineRequest = {
	requestId: string,
	expectedRevision: number,
	shrineInstanceId: string,
	expectedLevel: number,
	expectedMaterialId: string,
	expectedGoldCost: number,
	expectedMaterialQuantity: number,
}

export type DismantleShrineRequest = {
	requestId: string,
	expectedRevision: number,
	shrineInstanceId: string,
	expectedLevel: number,
}

export type EvolveMythlingRequest = {
	requestId: string,
	expectedRevision: number,
	workerId: string,
	expectedFormId: string,
	expectedTargetFormId: string,
}

export type SellMythlingRequest = {
	requestId: string,
	expectedRevision: number,
	workerId: string,
	expectedFormId: string,
	expectedGoldValue: number,
}

export type BaseRecord = {
	-- Transitional prototype ledger, independent of the new Shrine build slots.
	stands: { [string]: { production: StandProduction? } },
	-- Optional only at the load boundary and in retained prototype fixtures.
	buildSlotUpgrades: number?,
	shrines: { [string]: ShrineRecord }?,
	craftingStation: CraftingStationRecord?,
}

export type BaseStatus = {
	usedShrineSlots: number,
	unlockedShrineSlots: number,
	maxShrineSlots: number,
	craftingStation: CraftingStationRecord,
}

-- The player document held by DataService through ProfileStore.
export type PlayerDoc = {
	version: number,
	profile: {
		userId: number,
		createdAt: number,
		lastLoginAt: number,
	},
	mythlings: { [string]: MythlingEntry },
	inventoryUpgrades: { [string]: number }?,
	materials: { [string]: MaterialEntry },
	-- Legacy values are preserved opaquely; this cleanup does not activate Consumables.
	consumables: { [string]: unknown }?,
	currency: { [string]: number },
	equipment: { [string]: EquipmentEntry },
	transactions: TransactionState?,
	craftingJobs: { [string]: CraftingJob }?,
	-- Initialized from server time before exposure, never from a static template timestamp.
	productionClock: ProductionClock?,
	combatLoadout: {
		primaryWeaponInstanceId: string?,
		shieldInstanceId: string?,
	},
	base: BaseRecord,
}

export type StatePacket = {
	revision: number,
	-- This heterogeneous projection is decoded by LocalData's named-section boundary.
	-- Domain APIs expose their concrete records instead of carrying this dynamic shape onward.
	values: { [string]: any },
	removed: { string }?,
	full: boolean?,
}

export type ProductionStatus = {
	production: number,
	rate: number,
	capacity: number,
	progress: number,
	materials: { [string]: { stored: number, progress: number } },
	active: boolean,
	sampledAt: number,
}

export type StandProduction = {
	lastAccruedAt: number,
	materials: { [string]: { stored: number, progress: number } },
}

export type ProductionCollection = {
	collected: number,
	remaining: number,
	materials: { [string]: number },
}

export type CombatGuardRequest = {
	action: "Begin" | "Raised" | "Release" | "Lowered",
	sequence: number,
	character: Model,
}

export type CombatAttackRequest = { sequence: number, character: Model }

export type CombatHitReport = {
	sequence: number,
	character: Model,
	targetUserId: number,
	targetCharacter: Model,
}

export type CombatReactionType = "Launch" | "ShieldSlide"

export type CombatReaction = {
	hitId: number,
	character: Model,
	launchVelocity: Vector3,
	angularVelocity: Vector3,
	controlSeconds: number,
	reactionType: CombatReactionType,
	slideDurationSeconds: number,
	maximumReactionSeconds: number,
	landingRecoverySeconds: number,
}

export type InventoryCapacity = { used: number, limit: number }

export type ClaimMode = "Idle" | "Filling" | "Draining" | "Full"

export type ClaimUpdate = {
	userId: number,
	mythlingId: string?,
	mode: ClaimMode,
	progress: number,
	fillRate: number?,
	drainRate: number?,
	character: Model?,
	sampledAt: number,
}

export type Network = {
	Admin: { Feedback: RemoteEvent },
	State: { Update: RemoteEvent, Request: RemoteFunction },
	Inventory: { DeleteMythling: RemoteFunction },
	Production: { GetStatus: RemoteFunction, Collect: RemoteFunction },
	Base: { PlaceMythling: RemoteFunction, RemoveMythling: RemoteFunction },
	Combat: {
		StartAttack: RemoteEvent,
		ReportHit: RemoteEvent,
		SetShieldGuard: RemoteEvent,
		Reaction: RemoteEvent,
		Impact: RemoteEvent,
		GetLoadout: RemoteFunction,
		Equip: RemoteFunction,
	},
	World: { Spawned: RemoteEvent, ClaimState: RemoteEvent },
}

export type AdminCommandsConfiguration = {
	commandBurst: number,
	commandRefillPerSecond: number,
	streamTimeoutSeconds: number,
	arrivalPaddingStuds: number,
	groundProbeAboveStuds: number,
	groundProbeBelowStuds: number,
	minimumGroundNormalY: number,
	islandMarkerName: string,
	destinations: { [string]: { displayName: string, islandName: string } },
}

return {}
