--!strict
-- ReplicatedStorage/Shared/Configurations/MythlingForms
-- Permanent form identities and launch business metadata, not the active prototype spawn pool.

local FreezeUtil = require(script.Parent.Parent.FreezeUtil)
local Types = require(script.Parent.Parent.Types)

-- IDs never encode properties or change with names/assets. Add new IDs; never renumber or reuse.
-- Explicit per-form tuning is intentional: rarity/stage are not runtime stat formulas.
-- Names, lore, models, and thumbnails remain unset until the creative roster is approved.
local MythlingForms: { [string]: Types.MythlingFormDef } = {
	mythling_0001 = {
		element = "Fire",
		rarity = "Common",
		evolutionStage = 1,
		baseYieldPerHour = 12,
		captureProgressPerSecond = 100 / 20,
		captureDecayPerSecond = 100 / 20,
		evolution = { targetFormId = "mythling_0002", requiredLevel = 6 },
		sale = { gold = 25 },
	},
	mythling_0002 = {
		element = "Fire",
		rarity = "Rare",
		evolutionStage = 2,
		baseYieldPerHour = 18,
		captureProgressPerSecond = 100 / 35,
		captureDecayPerSecond = 100 / 35,
		evolution = { targetFormId = "mythling_0003", requiredLevel = 40 },
		sale = { gold = 100 },
	},
	mythling_0003 = {
		element = "Fire",
		rarity = "Epic",
		evolutionStage = 3,
		baseYieldPerHour = 32,
		captureProgressPerSecond = 100 / 60,
		captureDecayPerSecond = 100 / 60,
		sale = { gold = 300 },
	},
	mythling_0004 = {
		element = "Water",
		rarity = "Common",
		evolutionStage = 1,
		baseYieldPerHour = 12,
		captureProgressPerSecond = 100 / 20,
		captureDecayPerSecond = 100 / 20,
		evolution = { targetFormId = "mythling_0005", requiredLevel = 6 },
		sale = { gold = 25 },
	},
	mythling_0005 = {
		element = "Water",
		rarity = "Rare",
		evolutionStage = 2,
		baseYieldPerHour = 18,
		captureProgressPerSecond = 100 / 35,
		captureDecayPerSecond = 100 / 35,
		evolution = { targetFormId = "mythling_0006", requiredLevel = 40 },
		sale = { gold = 100 },
	},
	mythling_0006 = {
		element = "Water",
		rarity = "Epic",
		evolutionStage = 3,
		baseYieldPerHour = 32,
		captureProgressPerSecond = 100 / 60,
		captureDecayPerSecond = 100 / 60,
		sale = { gold = 300 },
	},
	mythling_0007 = {
		element = "Earth",
		rarity = "Common",
		evolutionStage = 1,
		baseYieldPerHour = 12,
		captureProgressPerSecond = 100 / 20,
		captureDecayPerSecond = 100 / 20,
		evolution = { targetFormId = "mythling_0008", requiredLevel = 6 },
		sale = { gold = 25 },
	},
	mythling_0008 = {
		element = "Earth",
		rarity = "Rare",
		evolutionStage = 2,
		baseYieldPerHour = 18,
		captureProgressPerSecond = 100 / 35,
		captureDecayPerSecond = 100 / 35,
		evolution = { targetFormId = "mythling_0009", requiredLevel = 40 },
		sale = { gold = 100 },
	},
	mythling_0009 = {
		element = "Earth",
		rarity = "Epic",
		evolutionStage = 3,
		baseYieldPerHour = 32,
		captureProgressPerSecond = 100 / 60,
		captureDecayPerSecond = 100 / 60,
		sale = { gold = 300 },
	},
	mythling_0010 = {
		element = "Air",
		rarity = "Common",
		evolutionStage = 1,
		baseYieldPerHour = 12,
		captureProgressPerSecond = 100 / 20,
		captureDecayPerSecond = 100 / 20,
		evolution = { targetFormId = "mythling_0011", requiredLevel = 6 },
		sale = { gold = 25 },
	},
	mythling_0011 = {
		element = "Air",
		rarity = "Rare",
		evolutionStage = 2,
		baseYieldPerHour = 18,
		captureProgressPerSecond = 100 / 35,
		captureDecayPerSecond = 100 / 35,
		evolution = { targetFormId = "mythling_0012", requiredLevel = 40 },
		sale = { gold = 100 },
	},
	mythling_0012 = {
		element = "Air",
		rarity = "Epic",
		evolutionStage = 3,
		baseYieldPerHour = 32,
		captureProgressPerSecond = 100 / 60,
		captureDecayPerSecond = 100 / 60,
		sale = { gold = 300 },
	},
	mythling_0013 = {
		element = "Light",
		rarity = "Common",
		evolutionStage = 1,
		baseYieldPerHour = 12,
		captureProgressPerSecond = 100 / 20,
		captureDecayPerSecond = 100 / 20,
		evolution = { targetFormId = "mythling_0014", requiredLevel = 6 },
		sale = { gold = 25 },
	},
	mythling_0014 = {
		element = "Light",
		rarity = "Rare",
		evolutionStage = 2,
		baseYieldPerHour = 18,
		captureProgressPerSecond = 100 / 35,
		captureDecayPerSecond = 100 / 35,
		evolution = { targetFormId = "mythling_0015", requiredLevel = 40 },
		sale = { gold = 100 },
	},
	mythling_0015 = {
		element = "Light",
		rarity = "Epic",
		evolutionStage = 3,
		baseYieldPerHour = 32,
		captureProgressPerSecond = 100 / 60,
		captureDecayPerSecond = 100 / 60,
		sale = { gold = 300 },
	},
	mythling_0016 = {
		element = "Dark",
		rarity = "Common",
		evolutionStage = 1,
		baseYieldPerHour = 12,
		captureProgressPerSecond = 100 / 20,
		captureDecayPerSecond = 100 / 20,
		evolution = { targetFormId = "mythling_0017", requiredLevel = 6 },
		sale = { gold = 25 },
	},
	mythling_0017 = {
		element = "Dark",
		rarity = "Rare",
		evolutionStage = 2,
		baseYieldPerHour = 18,
		captureProgressPerSecond = 100 / 35,
		captureDecayPerSecond = 100 / 35,
		evolution = { targetFormId = "mythling_0018", requiredLevel = 40 },
		sale = { gold = 100 },
	},
	mythling_0018 = {
		element = "Dark",
		rarity = "Epic",
		evolutionStage = 3,
		baseYieldPerHour = 32,
		captureProgressPerSecond = 100 / 60,
		captureDecayPerSecond = 100 / 60,
		sale = { gold = 300 },
	},
}

return FreezeUtil.DeepFreeze(MythlingForms)
